[package]
name = "niri-clip"
description = "为 niri + Wayland 设计的高性能开箱即用剪贴板历史管理器"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["niri", "wayland", "clipboard", "wl-clipboard", "cliphist"]
categories = ["command-line-utilities"]

[[bin]]
name = "niri-clip"
path = "src/main.rs"

[dependencies]
niri-clip-core.workspace = true
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
tokio.workspace = true
which.workspace = true
